### ISSUE TITLE
VS crashes after loading file with filter active and selecting result

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-visualstudio-extension#129] opened 2020-04-14 16:32 UTC
1. Open any SARIF file.
2. Apply a search filter (at top right of Error List window).
3. Double-click on any filtered result – no problem. The file opens.
4. _Without clearing the filter_, close and reopen the SARIF file.
5. Double-click on any filtered result – VS crashes.

[Bug129.sarif.txt](https://github.com/microsoft/sarif-visualstudio-extension/files/4504958/Bug129.sarif.txt) -- The SARIF file. Rename to .sarif.
[Bug129File.txt](https://github.com/microsoft/sarif-visualstudio-extension/files/4504959/Bug129File.txt) -- The data file used by the SARIF file.

@michaelcfanning FYI

**Comment by michaelcfanning** [comment] 2020-04-14 16:33
Wha? Actually repros with *any* SARIF file? :P

**Comment by lgolding** [comment] 2020-04-14 16:34
Yes.

**Comment by lgolding** [comment] 2020-04-14 16:46
This is the exception:

![image](https://user-images.githubusercontent.com/11762653/79251256-c6fba080-7e34-11ea-8456-fd43902926e6.png)

**Comment by lgolding** [comment] 2020-04-14 16:51
And if you hit this exception, for the love of all that's good don't press F5. That rebooted my computer.

**Comment by lgolding** [comment] 2020-07-13 20:30
This is not repro-ing any more with the attached file or with one other file I tried.

**Comment by michaelcfanning** [comment] 2020-07-13 21:35
OK. I just checked and it's definitely reproducing in VS2019 against latest master. Which VSIX/VS version did you test?

**Comment by lgolding** [comment] 2020-07-13 21:37
2.1.9

![image](https://user-images.githubusercontent.com/11762653/87356095-5721b280-c516-11ea-96eb-727276949db9.png)

**Comment by michaelcfanning** [comment] 2020-07-14 00:33
So the repro is straightforward: open a log file with any inlined content, like an embedded link. Type something in the search filter (that still permits a result with an inlined link to display), double-click the result with the inlined link.

Can you test this? Crashes reliably on my machine with shipping VSIX. Debugger shows that WPF is attempting to access WPF text runs on a thread that it doesn't think is associated with the UI object. Looks like this is what's bringing down the process. What's confusing is that this seems to be happening on the UI thread, so not sure what's going on here. We need @EasyRhinoMSFT to comment, I think, :)

**Comment by EasyRhinoMSFT** [comment] 2020-07-14 11:52
Yeesh, let me see if I can remember how to debug this thing and have a look. 😊

**Comment by michaelcfanning** [comment] 2020-07-16 17:42
Chased down. We were, in fact, creating 'Inline' object instances on a background thread. Now have instrumented this creation helper to synchronize to the UI thread, if necessary, before construction.

Resolved by https://github.com/microsoft/sarif-visualstudio-extension/pull/120

**Closed** 2020-07-16 17:42 UTC
Labels: bug
