### ISSUE TITLE
Sarif Viewer VS extension does not support codeflows

### ISSUE THREAD

**Issue by xi-liu-ds** [microsoft/sarif-visualstudio-extension#449] opened 2021-12-13 19:39 UTC
Hi,

We found that Sarif Viewer VS extension does not support `codeFlow` property in Sarif file. We are wondering do you have a timeline to support it? Thanks!

**Comment by eddynaka** [comment] 2021-12-13 19:44
@yongyan-gh, can you create a SARIF with CodeFlow properties, test in vscode, and see if that appears correctly in both tools?

**Comment by xi-liu-ds** [comment] 2021-12-14 17:33
I see. I have double checked. It seems that if drop the `physicalLocation` in codeflows, Sarif Viewer extension aren't able to load it? For example:

```
{
    "$schema": "http://json.schemastore.org/sarif-2.1.0-rtm.5",
    "version": "2.1.0",
    "runs": [
        {
            "tool": {
                "driver": {
                    "name": "Infer",
                    "informationUri": "https://github.com/facebook/infer",
                    "version": "1.1.0",
                    "rules": [
                        {
                            "id": "NULLPTR_DEREFERENCE",
                            "shortDescription": {
                                "text": "Null Dereference"
                            }
                        }
                    ]
                }
            },
            "results": [
                {
                    "message": {
                        "text": "Pulse found a potential null pointer dereference on line 41."
                    },
                    "level": "error",
                    "ruleId": "NULLPTR_DEREFERENCE",
                    "codeFlows": [
                        {
                            "threadFlows": [
                                {
                                    "locations": [
                                        {
                                            "nestingLevel": 1,
                                            "location": {
                                                "message": {
                                                    "text": "in call to `Object Program.ReturnNullReference()`"
                                                }
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ],
                    "locations": [
                        {
                            "physicalLocation": {
                                "artifactLocation": {
                                    "uri": "file:C:\\Users\\matjin\\source\\repos\\ConsoleApp4\\ConsoleApp4\\Program.cs",
                                    "uriBaseId": "/root/C:\\Users\\matjin\\source\\repos\\ConsoleApp4\\ConsoleApp4\\Program.cs"
                                },
                                "region": {
                                    "startLine": 41,
                                    "startColumn": 13
                                }
                            }
                        }
                    ]
                }
            ]
        }
    ]
}
```

**Comment by yongyan-gh** [comment] 2021-12-15 01:18
The issue that SARIF viewer does not show codeflow property of above result in SARIF explorer is because the 'nestingLevel' of threadFlow.location. [SARIF spec](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317761)

The viewer tries to create code flows in a tree view based on threadFlow.location.nestingLevel property. It assumes nestingLevel 0, also the default value, to be the root node, and child nodes have nestingLevel greater than 0.

In above result the 'nestingLevel' of the only threadFlow.location is 1, viewer cannot find the root node to render the tree view. 
You can set the nestingLevel value starting from 0, this will unblock you from the issue.
Will double check with SARIF team about the what should be expected behavior. 

Thanks!

**Comment by xi-liu-ds** [comment] 2021-12-15 02:01
> The issue that SARIF viewer does not show codeflow property of above result in SARIF explorer is because the 'nestingLevel' of threadFlow.location. [SARIF spec](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317761)
> 
> The viewer tries to create code flows in a tree view based on threadFlow.location.nestingLevel property. It assumes nestingLevel 0, also the default value, to be the root node, and child nodes have nestingLevel greater than 0.
> 
> In above result the 'nestingLevel' of the only threadFlow.location is 1, viewer cannot find the root node to render the tree view. You can set the nestingLevel value starting from 0, this will unblock you from the issue. Will double check with SARIF team about the what should be expected behavior.
> 
> Thanks!

I see. Thanks for looking into this. We found that level 1 is supported in Sarif Viewer VS Code extension: 

![image](https://user-images.githubusercontent.com/63893533/146109250-75b914de-9b7b-4a00-97c1-8e34ae245bc4.png)

Maybe these is an inconsistency here?

**Comment by yongyan-gh** [comment] 2021-12-16 23:57
@xi-liu-ds the SARIF viewer VS code extension renders the threadFlowLocations as a flat list, the VS extension supports rendering threadFlowLocations to a tree view based on the nestingLevel. e.g. below screenshot shows a tree view of nested threadFlowLocations.

![image](https://user-images.githubusercontent.com/76094515/146464788-ab915686-ed8e-4333-9b4e-01483ae253a3.png)

We would like to have better understanding about the what information do you capture in the codeflow properties and how would you like the viewer to show that information. Can you please share couple SARIF samples created by your tool include codeflows data? Does the codeflow have single or multiple threadFlowLocations in your cases? Are they captured in a hierarchical structure? Thanks!

**Comment by matjin** [comment] 2021-12-17 21:26
Hi!

Here is an example SARIF file that we would like to render:

{
    "$schema": "http://json.schemastore.org/sarif-2.1.0-rtm.5",
    "version": "2.1.0",
    "runs": [
        {
            "tool": {
                "driver": {
                    "name": "Infer",
                    "informationUri": "https://github.com/facebook/infer",
                    "version": "1.1.0",
                    "rules": [
                        {
                            "id": "DOTNET_RESOURCE_LEAK",
                            "shortDescription": {
                                "text": "Dotnet Resource Leak"
                            },
                            "helpUri": "https://fbinfer.com/docs/next/all-issue-types#dotnet_resource_leak"
                        },
                        {
                            "id": "NULLPTR_DEREFERENCE",
                            "shortDescription": {
                                "text": "Null Dereference"
                            },
                            "helpUri": "https://fbinfer.com/docs/next/all-issue-types#nullptr_dereference"
                        },
                        {
                            "id": "THREAD_SAFETY_VIOLATION",
                            "shortDescription": {
                                "text": "Thread Safety Violation"
                            },
                            "helpUri": "https://fbinfer.com/docs/next/all-issue-types#thread_safety_violation"
                        }
                    ]
                }
            },
            "results": [
                {
                    "message": {
                        "text": "Leaked { %1 -> 1, %0 -> 1 } resource(s) in method \"Void Program.CreateResourceStreamLeak()\" at type(s) System.IO.StreamReader, System.IO.FileStream."
                    },
                    "level": "error",
                    "ruleId": "DOTNET_RESOURCE_LEAK",
                    "locations": [
                        {
                            "physicalLocation": {
                                "artifactLocation": {
                                    "uri": "file:C:\\Users\\matjin\\source\\repos\\ConsoleApp4\\ConsoleApp4\\Program.cs",
                                    "uriBaseId": "/root/C:\\Users\\matjin\\source\\repos\\ConsoleApp4\\ConsoleApp4\\Program.cs"
                                },
                                "region": {
                                    "startLine": 19,
                                    "startColumn": 9
                                }
                            }
                        }
                    ]
                },
                {
                    "message": {
                        "text": "Leaked { n$0 -> 1, %0.ConsoleApp4.ResourceOwner.streamWriter -> -1 } resource(s) in method \"Void Program.ShouldNotLeak()\" at type(s) System.IO.StreamWriter."
                    },
                    "level": "error",
                    "ruleId": "DOTNET_RESOURCE_LEAK",
                    "locations": [
                        {
                            "physicalLocation": {
                                "artifactLocation": {
                                    "uri": "file:C:\\Users\\matjin\\source\\repos\\ConsoleApp4\\ConsoleApp4\\Program.cs",
                                    "uriBaseId": "/root/C:\\Users\\matjin\\source\\repos\\ConsoleApp4\\ConsoleApp4\\Program.cs"
                                },
                                "region": {
                                    "startLine": 26,
                                    "startColumn": 9
                                }
                            }
                        }
                    ]
                },
                {
                    "message": {
                        "text": "Pulse found a potential null pointer dereference on line 41."
                    },
                    "level": "error",
                    "ruleId": "NULLPTR_DEREFERENCE",
                    "codeFlows": [
                        {
                            "threadFlows": [
                                {
                                    "locations": [
                                        {
                                            "nestingLevel": 1,
                                            "location": {
                                                "physicalLocation": {
                                                    "artifactLocation": {
                                                        "uri": "file:C:\\Users\\matjin\\source\\repos\\ConsoleApp4\\ConsoleApp4\\Program.cs",
                                                        "uriBaseId": "/root/C:\\Users\\matjin\\source\\repos\\ConsoleApp4\\ConsoleApp4\\Program.cs"
                                                    },
                                                    "region": {
                                                        "startLine": 40,
                                                        "startColumn": 13
                                                    }
                                                },
                                                "message": {
                                                    "text": "in call to `Object Program.ReturnNullReference()`"
                                                }
                                            }
                                        },
                                        {
                                            "nestingLevel": 2,
                                            "location": {
                                                "physicalLocation": {
                                                    "artifactLocation": {
                                                        "uri": "file:C:\\Users\\matjin\\source\\repos\\ConsoleApp4\\ConsoleApp4\\Program.cs",
                                                        "uriBaseId": "/root/C:\\Users\\matjin\\source\\repos\\ConsoleApp4\\ConsoleApp4\\Program.cs"
                                                    },
                                                    "region": {
                                                        "startLine": 35,
                                                        "startColumn": 13
                                                    }
                                                },
                                                "message": {
                                                    "text": "is the null pointer"
                                                }
                                            }
                                        },
                                        {
                                            "nestingLevel": 2,
                                            "location": {
                                                "physicalLocation": {
                                                    "artifactLocation": {
                                                        "uri": "file:C:\\Users\\matjin\\source\\repos\\ConsoleApp4\\ConsoleApp4\\Program.cs",
                                                        "uriBaseId": "/root/C:\\Users\\matjin\\source\\repos\\ConsoleApp4\\ConsoleApp4\\Program.cs"
                                                    },
                                                    "region": {
                                                        "startLine": 35,
                                                        "startColumn": 13
                                                    }
                                                },
                                                "message": {
                                                    "text": "assigned"
                                                }
                                            }
                                        },
                                        {
                                            "nestingLevel": 2,
                                            "location": {
                                                "physicalLocation": {
                                                    "artifactLocation": {
                                                        "uri": "file:C:\\Users\\matjin\\source\\repos\\ConsoleApp4\\ConsoleApp4\\Program.cs",
                                                        "uriBaseId": "/root/C:\\Users\\matjin\\source\\repos\\ConsoleApp4\\ConsoleApp4\\Program.cs"
                                                    },
                                                    "region": {
                                                        "startLine": 36,
                                                        "startColumn": 9
                                                    }
                                                },
                                                "message": {
                                                    "text": "returned"
                                                }
                                            }
                                        },
                                        {
                                            "nestingLevel": 1,
                                            "location": {
                                                "physicalLocation": {
                                                    "artifactLocation": {
                                                        "uri": "file:C:\\Users\\matjin\\source\\repos\\ConsoleApp4\\ConsoleApp4\\Program.cs",
                                                        "uriBaseId": "/root/C:\\Users\\matjin\\source\\repos\\ConsoleApp4\\ConsoleApp4\\Program.cs"
                                                    },
                                                    "region": {
                                                        "startLine": 40,
                                                        "startColumn": 13
                                                    }
                                                },
                                                "message": {
                                                    "text": "return from call to `Object Program.ReturnNullReference()`"
                                                }
                                            }
                                        },
                                        {
                                            "nestingLevel": 1,
                                            "location": {
                                                "physicalLocation": {
                                                    "artifactLocation": {
                                                        "uri": "file:C:\\Users\\matjin\\source\\repos\\ConsoleApp4\\ConsoleApp4\\Program.cs",
                                                        "uriBaseId": "/root/C:\\Users\\matjin\\source\\repos\\ConsoleApp4\\ConsoleApp4\\Program.cs"
                                                    },
                                                    "region": {
                                                        "startLine": 40,
                                                        "startColumn": 13
                                                    }
                                                },
                                                "message": {
                                                    "text": "assigned"
                                                }
                                            }
                                        },
                                        {
                                            "nestingLevel": 1,
                                            "location": {
                                                "physicalLocation": {
                                                    "artifactLocation": {
                                                        "uri": "file:C:\\Users\\matjin\\source\\repos\\ConsoleApp4\\ConsoleApp4\\Program.cs",
                                                        "uriBaseId": "/root/C:\\Users\\matjin\\source\\repos\\ConsoleApp4\\ConsoleApp4\\Program.cs"
                                                    },
                                                    "region": {
                                                        "startLine": 41,
                                                        "startColumn": 13
                                                    }
                                                },
                                                "message": {
                                                    "text": "invalid access occurs here"
                                                }
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ],
                    "locations": [
                        {
                            "physicalLocation": {
                                "artifactLocation": {
                                    "uri": "file:C:\\Users\\matjin\\source\\repos\\ConsoleApp4\\ConsoleApp4\\Program.cs",
                                    "uriBaseId": "/root/C:\\Users\\matjin\\source\\repos\\ConsoleApp4\\ConsoleApp4\\Program.cs"
                                },
                                "region": {
                                    "startLine": 41,
                                    "startColumn": 13
                                }
                            }
                        }
                    ]
                },
                {
                    "message": {
                        "text": "Read/Write race. Non-private method `Program.GetIntValue()` reads without synchronization from `this.ConsoleApp4.Program.intValue`. Potentially races with write in method `Program.SetIntValue()`.\n Reporting because another access to the same memory occurs on a background thread, although this access may not."
                    },
                    "level": "warning",
                    "ruleId": "THREAD_SAFETY_VIOLATION",
                    "codeFlows": [
                        {
                            "threadFlows": [
                                {
                                    "locations": [
                                        {
                                            "nestingLevel": 0,
                                            "location": {
                                                "physicalLocation": {
                                                    "artifactLocation": {
                                                        "uri": "file:C:\\Users\\matjin\\source\\repos\\ConsoleApp4\\ConsoleApp4\\Program.cs",
                                                        "uriBaseId": "/root/C:\\Users\\matjin\\source\\repos\\ConsoleApp4\\ConsoleApp4\\Program.cs"
                                                    },
                                                    "region": {
                                                        "startLine": 49,
                                                        "startColumn": 13
                                                    }
                                                },
                                                "message": {
                                                    "text": "<Read trace>"
                                                }
                                            }
                                        },
                                        {
                                            "nestingLevel": 0,
                                            "location": {
                                                "physicalLocation": {
                                                    "artifactLocation": {
                                                        "uri": "file:C:\\Users\\matjin\\source\\repos\\ConsoleApp4\\ConsoleApp4\\Program.cs",
                                                        "uriBaseId": "/root/C:\\Users\\matjin\\source\\repos\\ConsoleApp4\\ConsoleApp4\\Program.cs"
                                                    },
                                                    "region": {
                                                        "startLine": 49,
                                                        "startColumn": 13
                                                    }
                                                },
                                                "message": {
                                                    "text": "access to `this.ConsoleApp4.Program.intValue`"
                                                }
                                            }
                                        },
                                        {
                                            "nestingLevel": 0,
                                            "location": {
                                                "physicalLocation": {
                                                    "artifactLocation": {
                                                        "uri": "file:C:\\Users\\matjin\\source\\repos\\ConsoleApp4\\ConsoleApp4\\Program.cs",
                                                        "uriBaseId": "/root/C:\\Users\\matjin\\source\\repos\\ConsoleApp4\\ConsoleApp4\\Program.cs"
                                                    },
                                                    "region": {
                                                        "startLine": 56,
                                                        "startColumn": 17
                                                    }
                                                },
                                                "message": {
                                                    "text": "<Write trace>"
                                                }
                                            }
                                        },
                                        {
                                            "nestingLevel": 0,
                                            "location": {
                                                "physicalLocation": {
                                                    "artifactLocation": {
                                                        "uri": "file:C:\\Users\\matjin\\source\\repos\\ConsoleApp4\\ConsoleApp4\\Program.cs",
                                                        "uriBaseId": "/root/C:\\Users\\matjin\\source\\repos\\ConsoleApp4\\ConsoleApp4\\Program.cs"
                                                    },
                                                    "region": {
                                                        "startLine": 56,
                                                        "startColumn": 17
                                                    }
                                                },
                                                "message": {
                                                    "text": "access to `this.ConsoleApp4.Program.intValue`"
                                                }
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ],
                    "locations": [
                        {
                            "physicalLocation": {
                                "artifactLocation": {
                                    "uri": "file:C:\\Users\\matjin\\source\\repos\\ConsoleApp4\\ConsoleApp4\\Program.cs",
                                    "uriBaseId": "/root/C:\\Users\\matjin\\source\\repos\\ConsoleApp4\\ConsoleApp4\\Program.cs"
                                },
                                "region": {
                                    "startLine": 49,
                                    "startColumn": 13
                                }
                            }
                        }
                    ]
                },
                {
                    "message": {
                        "text": "Leaked { %0 -> 1 } resource(s) in method \"Void Program.ResourceLeakBad()\" at type(s) System.IO.StreamWriter."
                    },
                    "level": "error",
                    "ruleId": "DOTNET_RESOURCE_LEAK",
                    "locations": [
                        {
                            "physicalLocation": {
                                "artifactLocation": {
                                    "uri": "file:C:\\Users\\matjin\\source\\repos\\ConsoleApp4\\ConsoleApp4\\Program.cs",
                                    "uriBaseId": "/root/C:\\Users\\matjin\\source\\repos\\ConsoleApp4\\ConsoleApp4\\Program.cs"
                                },
                                "region": {
                                    "startLine": 68,
                                    "startColumn": 9
                                }
                            }
                        }
                    ]
                }
            ]
        }
    ]
}

**Comment by yongyan-gh** [comment] 2021-12-21 20:17
thank you @matjin sharing your SARIF result. I see there are 2 kinds of threadFlows in the SARIF file.
1. All threadFlow locations have nestingLevel set to 0.
  In this case SARIF viewer is able to render the all the locations in root node.
2. ThreadFlow locations nestingLevel starts from 1, there are 2nd level locations (nestingLevel is 2). 
  In this case SARIF viewer cannot render the codeflows since it assume the nestingLevel starts from 0. After updated the nestingLevel with starting value to 0, viewer can render the locations in tree view.
  Couple questions: 
  Do you intend to set the start value of nestingLevel to 1? Can you set the value starts from 0?
  Do you expect the viewer to render the locations in a tree view so it can have parent/child nodes?


Also have a suggestion for your SARIF result:
the "uriBaseId" property of artifactLocation should be an identifier reference to "originalUriBaseIds" dictionary under Run object.
You can define a uriBaseId points to a root location of the code base. Then in artifactLocation you can specify uriBaseId and relative path in uri property. E.g.
Have a uriBaseId "SRCROOT" defined in originalUriBaseIds, points to a repo location.
```
            "originalUriBaseIds": {
                "SRCROOT": {
                    "uri": "file:///C:/Users/matjin/source/repos/ConsoleApp4/"
                }
            }
```
in artifactLocation you can set uriBaseId to "SRCROOT" and use relative path as uri to point to a source file.
```
                            "physicalLocation": {
                                "artifactLocation": {
                                    "uri": "ConsoleApp4/Program.cs",
                                    "uriBaseId": "SRCROOT"
                                },
```

**Comment by matjin** [comment] 2022-01-05 00:13
Hi @yongyan-gh!

Thank you for the suggestion. @xi-liu-ds will look into that.

To answer your questions first:
Do you intend to set the start value of nestingLevel to 1? Can you set the value starts from 0?
**The fields are set by an upstream process so it wouldn't be simple for us to hack that to start from 0. However, SARIF Viewer VSCode is robust enough to render the same file, so I wonder if that same robustness can be carried into SARIF Viewer VS**

Do you expect the viewer to render the locations in a tree view so it can have parent/child nodes?
**The viewer does not have to render in tree mode for my scenario.**

Would it be possible for this to be resolved on the extension end, as the functionality holds in VSCode SARIF Viewer?

**Comment by yongyan-gh** [comment] 2022-01-05 21:02
Thanks @matjin for the information,
we are investigating the issue and will work on a proper solution.

**Comment by matjin** [comment] 2022-01-18 19:48
Saw the fix! @yongyan-gh is it ready? Thanks!

**Comment by xi-liu-ds** [comment] 2022-01-26 20:06
@yongyan-gh I saw the fix is merged. Was it also released in extension already?

**Comment by yongyan-gh** [comment] 2022-01-26 20:26
@matjin / @xi-liu-ds 

Thanks for your feedbacks. We have the fix for the codeflow issue in VS extension. However, we have some bugs/items need to be addressed before publishing a new release.

If you would like to try the latest version including codeflow issue, you can enlist the repo and build the vsix following below steps:
1.	Clone the repo in your local drive.
2.	Open VS developer command prompt/powershell navigate to repo’s root folder.
3.	Run command: “BuildAndTest.cmd”.
4.	You can find the VSIX in repo root\bld\bin\ folder.

If you have issue not able to build, pls let me know I can share the latest vsix to you.

**Comment by xi-liu-ds** [comment] 2022-01-27 05:51
> @matjin / @xi-liu-ds
> 
> Thanks for your feedbacks. We have the fix for the codeflow issue in VS extension. However, we have some bugs/items need to be addressed before publishing a new release.
> 
> If you would like to try the latest version including codeflow issue, you can enlist the repo and build the vsix following below steps:
> 
> 1. Clone the repo in your local drive.
> 2. Open VS developer command prompt/powershell navigate to repo’s root folder.
> 3. Run command: “BuildAndTest.cmd”.
> 4. You can find the VSIX in repo root\bld\bin\ folder.
> 
> If you have issue not able to build, pls let me know I can share the latest vsix to you.

Will try. Thanks!

**Comment by EasyRhinoMSFT** [comment] 2022-02-10 23:39
@matjin @xi-liu-ds FYI, this change was included in a new version of the extension that was published yesterday.

**Comment by EasyRhinoMSFT** [comment] 2022-10-03 20:29
Closing as the issue is presumed fixed, @matjin @xi-liu-ds please re-open if necessary.

**Closed by EasyRhinoMSFT** 2022-10-03 20:29 UTC
