### ISSUE TITLE
VS doesn't extract and display files in the absence of region data

### ISSUE THREAD

**Issue by michaelcfanning** [microsoft/sarif-visualstudio-extension#121] opened 2020-04-07 20:13 UTC
* Create a SARIF file w/results that reference artifacts with textual or binary contents data (but no regions associated with results.
* Open SARIF file in VS viewer and double-click result.

**Result**
File isn't expanded from log file and loaded into viewer.

If a modify the log file to add any sort of region to the result location physicalLocation, everything works as expected.

@lgolding

**Comment by lgolding** [comment] 2020-04-07 21:24
Here is a repro file:

1. Save this file with extension .sarif (drop the .txt extension):

    [Bug121.sarif.txt](https://github.com/microsoft/sarif-visualstudio-extension/files/4447045/Bug121.sarif.txt)

2. Open the file in VS

3. In the Error List window, double-click the single result.

    The viewer extracts the file contents, displays them in an editor window, and highlights the second line.

4. Now remove the region object (lines 42-44) and re-open the file.

    Now when you double-click on the result, nothing happens.

**Comment by lgolding** [comment] 2020-04-10 18:28
Duplicate of #119, the same fix takes care of both.

**Closed** 2020-04-10 18:28 UTC
Labels: bug, resolved-duplicate
