### ISSUE TITLE
Alerts not mapped to source code

### ISSUE THREAD

**Issue by mokrz** [microsoft/sarif-visualstudio-extension#366] opened 2021-02-03 21:19 UTC
We have a customer trying to use the Microsoft SARIF Viewer extension with Visual Studio 2019, but they're having problems mapping alerts from the SARIF file(s) to affected portions of their source code. They summarized it pretty well in their ticket description, so I'll just include that here:

For some reason it doesn't seem to map the alerts exported into SARIF format from Semmle to the solution (source code) opened in Visual Studio 2019. Every time I click on a Semmle alert imported into Visual Studio 2019, it prompts me to open the file path of the source code file where the alert is triggered even though I have the entire codebase (solution) open in Visual Studio 2019.

I'll be requesting the SLN and SARIF log file from the customer sometime today, I'll likely hear back from them tomorrow. Feel free to reach out to me for additional details in the meantime!

**Comment by michaelcfanning** [comment] 2021-02-04 15:59
@eddynaka @yongyan-gh 

Yong, can we please make fixing this a high priority? I don't think it will be super difficult. When a double-click on a SARIF error list result provokes a file remapping response, check to see if a SLN is loaded and, if so, see if the $(SolutionDir) directory location can be merged with the SARIF file path to locate the file. There could be an interesting complication, in that the tool may have pointed to an enlistment root, while the SLN is in a more interior location. 

The tool in question here is CodeQL and Eddy can provide an example of its output (which elides non-deterministic enlistment roots by default, as is recommended).

**Comment by yongyan-gh** [comment] 2021-02-04 21:11
Below are what happens when user click on SARIF error list result:
1. At the first time, sarif extension cannot resolve the base URI e.g. %SRCROOT% or $(SolutionDir), it pops up open file dialog ask user to select the right file path. (Remapping)
2. Extension saves the base URI in a cache 
3. Click on another error list result, extension can resolve full file path since base URI was resolved and cached, no remapping needed, it can open the file associated with the error.

Checked with Eddy, we should try to resolve the path using solution directory if the solution is opened in VS, so that we can avoid the file path remapping in step 1.

@michaelcfanning/@mokrz can you pls confirm?

**Comment by mokrz** [comment] 2021-02-04 21:20
That sounds right to me, but I haven't worked with VS much so I can't say for certain.
/cc @michaelcfanning (looks like the above mention didn't work).

**Comment by eddynaka** [comment] 2021-02-04 21:57
> Below are what happens when user click on SARIF error list result:
> 
> 1. At the first time, sarif extension cannot resolve the base URI e.g. %SRCROOT% or $(SolutionDir), it pops up open file dialog ask user to select the right file path. (Remapping)
> 2. Extension saves the base URI in a cache
> 3. Click on another error list result, extension can resolve full file path since base URI was resolved and cached, no remapping needed, it can open the file associated with the error.
> 
> Checked with Eddy, we should try to resolve the path using solution directory if the solution is opened in VS, so that we can avoid the file path remapping in step 1.
> 
> @michaelcfanning/@mokrz can you pls confirm?

yes, confirmed with Michael!

**Comment by michaelcfanning** [comment] 2021-02-04 21:57
Yes, Yong, that's correct.

**Comment by eddynaka** [comment] 2021-02-08 20:39
With the merged PR we will fix this. Probably will release a new version this weekend.

**Closed** 2021-02-08 20:46 UTC
