### ISSUE TITLE
Light bulbs don't appear if source file is opened before the SARIF log file is opened

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-visualstudio-extension#247] opened 2020-11-02 20:16 UTC
@michaelcfanning @GabeDeBacker 

Gabe, I know you ran into something similar with tags.

**Comment by michaelcfanning** [comment] 2020-11-02 20:45
Very nice to see this class of bug coming in, which I assume may be turning up due to ad hoc testing? If so, let's be sure that we add appropriate unit and functional tests to cover these scenarios before declaring victory on the issue. :)

**Comment by lgolding** [comment] 2020-11-02 21:06
Yes, from _ad hoc_ testing. Unit testing this stuff is tough but I'll do what I can. We have #197 tracking Apex-based UI testing as well.

**Comment by michaelcfanning** [comment] 2020-11-02 21:59
Please don't feel like you need to tie yourself in knots unit-testing something that will be more easily accomplish in our functional test harness. You might find some inspiration for test methodology that can be driven via the unit-test harness by searching for MVVM unit test patterns. IOW, if we can validate that the view models do the right thing, we can then use the end-to-end testing to add the actual view on top of these.

Once we get past adding some in-memory mechanisms to drive the SARIF viewer, #197 is definitely a high priority.

**Comment by yongyan-gh** [comment] 2021-02-27 02:35
This issue should be fixed by #368. 

Below change was to make sure Sarif viewer package is loaded after Sarif log loaded.

The package is inherited from AsyncPackage, it only loads if its triggered from UI action like menu click etc. unless we explicitly load it programmatically.

https://github.com/microsoft/sarif-visualstudio-extension/blob/2aa6708d24ec078619155a3cea80c74fde999d82/src/Sarif.Viewer.VisualStudio/ErrorList/ErrorListService.cs#L660-L671

**Comment by yongyan-gh** [comment] 2021-06-29 08:31
root cause: 
To show the suggestion action aka light bulb in VS editor, we implemented [FixSuggestedActionsSource](https://github.com/microsoft/sarif-visualstudio-extension/blob/main/src/Sarif.Viewer.VisualStudio/Fixes/FixSuggestedActionsSource.cs) inherited from Microsoft.VisualStudio.Language.Intellisense.ISuggestedActionsSource. 

When a document/text buffer is opened in VS editor, VS will call this class to get suggestion actions, our code is looking for any error list item from sarif log is associated with current opened file.

if we open sarif log and load results into error list first, when navigate to an error it opens the file in editor and trigger FixSuggestedActionsSource, it can get associated error list item.

if we open the file first, the FixSuggestedActionsSource cannot find error list items related to current file, since the sarif log is not opened yet. 

FixSuggestedActionsSource does listen to ErrorListTableControl.EntriesChanged event, even the sarif log is loaded later, VS will fire the event, it will try to refresh/re-calculate the suggestion actions. However, this calculation checks if current opened document file path, a full file path, is same as error list item's file path, its usually a relative path with base Uri id, e.g.
                "artifactLocation": {
                  "uri": "fixes.txt",
                  "uriBaseId": "REPO_ROOT"
                }
and the error list item's file path is the relative path when sarif log is loaded, only when user navigate to that error list item, e.g. double click error list item, we will try to resolve the file path to a full path.

This is the reason why the suggestion actions/light bulbs don't show if source file is opened before Sarif log is loaded.

I think we probably can go below 2 approaches to resolve the problem:
- Let FixSuggestedActionsSource listen to right event so that it can always get right error list items to create suggestion actions.
- Or update the logic finding right error list items related to current opened source file (full path vs relative path).

**Closed** 2021-06-30 00:37 UTC
Labels: bug
